# Perceptron network for depicting AND function

In [22]:
#importing libraries
import pandas as pd
import numpy as np

In [23]:
#creating arrays for inputs
x1 = np.array([1, 1, 0, 0])
x2 = np.array([1, 0, 1, 0])
t = np.array([1, 0, 0, 0])

In [24]:
#dictionary for dataframe
X = {'x1':[1, 1, -1, -1], 'x2':[1, -1, 1, -1], 't':[1, -1, -1, -1]}

In [25]:
#this dataframe is being prepared for quick reference
df = pd.DataFrame(X, columns = ('x1', 'x2', 't'))

In [26]:
#Dataframe of AND lagic function
df

x1  x2  t
0   1   1  1
1   1  -1 -1
2  -1   1 -1
3  -1  -1 -1

In [27]:
#Creating input value arrays
x0 = np.array(df.iloc[0,:2])

In [28]:
x0

array([1, 1], dtype=int64)

In [29]:
x1 = np.array(df.iloc[1,:2])
x2 = np.array(df.iloc[2,:2])
x3 = np.array(df.iloc[3,:2])

In [30]:
#Activation function
def activate(y):
    if y > 0:
        return 1
    elif y == 0:
        return 0
    elif y < 0:
        return -1

In [31]:
#Traget value variables
y0 = df.iloc[0,2]
y1 = df.iloc[1,2]
y2 = df.iloc[2,2]
y3 = df.iloc[3,2]

In [32]:
#Traget value variables
t = np.array([y0,y1,y2,y3])
t

array([ 1, -1, -1, -1], dtype=int64)

In [33]:
#Array for inputs from variables
yin = np.zeros(4)
yin

array([0., 0., 0., 0.])

In [34]:
#Input Variables matrix
x = np.array([x0,x1,x2,x3])
print(x)

[[ 1  1]
 [ 1 -1]
 [-1  1]
 [-1 -1]]


In [35]:
#Weights and bias
w = np.array([0,0])
b = 1

In [36]:
#Training the network 
alpha = 1                      #Alpha -- Learning Rate
for i in range(len(x)):        #Iterating over till all the value pairs ar
    flag = 0
    for (j,k,l) in zip(x,yin,t):
        y = np.dot(w,j.T) + b
        k = activate(y)
        if k!=l:
            w[0] = w[0] + alpha * j[0] * l
            w[1] = w[1] + alpha * j[1] * l
            b = b + alpha * l
            flag = 1
        else:
            w[0] = w[0]
            w[1] = w[1]
            b = b
    if flag == 1:
        continue
    elif flag == 0:
        break

In [37]:
w

array([2, 2])

In [38]:
xx = np.array([-1,-1])
yin = activate(np.dot(w,xx.T) + b)
print(yin)

-1
